### ISSUE TITLE
Document original lighthouse score

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/palladium#2]
We should establish the list of urls of https://www.palladiumhotelgroup.com/es/cares/4-causas/infancia and its subpages and document (screenshot plus values captured in a table) the respective pagespeed results (https://pagespeed.web.dev/). 

Probably a good idea to create a new top-level `docs` folder and a subfolder in there with results.

**Comment by RemoLiechti** [comment]
See https://github.com/hlxsites/palladium/blob/features/2-DocumentOriginalLighthouseScore/docs/LHScores/lhs-scores.csv
