### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/palladium#24]
- [x] Content (copy/paste)
- [x] Desktop rendering
- [ ] Mobile rendering

<img width="1433" alt="Screenshot 2023-09-06 at 10 01 14" src="https://github.com/hlxsites/palladium/assets/111385/d3a1e0a8-f5d2-4d71-ad64-2f8775eda7f8">

**Comment by paolomoz** [comment]
@Subrat-Code-94 see current version of footer content, feel free to adjust https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B0670F843-D8E7-42AA-AD8C-847A989835A7%7D&file=footer.docx&action=default&mobileredirect=true

**Comment by Subrat-Code-94** [comment]
@paolomoz I am not able to access the above share point link to view the footer content. Can you please provide the access.

**Comment by paolomoz** [comment]
> @paolomoz I am not able to access the above share point link to view the footer content. Can you please provide the access.

done, could you please check and confirm?
